version: '3.2'
services:
  kafka:
    image: johnnypark/kafka-zookeeper
    container_name: kafka
    environment: 
      ADVERTISED_HOST: 127.0.0.1
      NUM_PARTITIONS: 10
    ports:
      - "2181:2181"
      - "9092:9092"
    restart: unless-stopped

  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elastic-search
    ports:
      - "9200:9200"
      - "9300:9300"
    networks: 
      - elastic-stack
    restart: unless-stopped
    environment:
      discovery.type: single-node
    volumes: 
      - elastic-search-vol:/usr/share/elasticsearch/data
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: kibana
    ports:
      - "5601:5601"
    networks: 
      - elastic-stack
    restart: unless-stopped
    depends_on:
      - elastic-search
    environment:
      ELASTICSEARCH_URL: http://elastic-search:9200
      ELASTICSEARCH_HOSTS: http://elastic-search:9200

networks: 
  elatic-stack:
    driver: bridge

volumes:
  elastic-search-vol: